### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by dacbarbos** [pegacat/jxplorer#2]
Q: While both [license.html](http://jxplorer.org/licence.html) and license.txt @ [SourceForge](https://sourceforge.net/p/jxplorer/code/HEAD/tree/licence.txt) and [GitHub](https://github.com/pegacat/jxplorer/blob/master/licence.txt) use a simple **CAOSL v1.0**, I've noticed there is a newer **CATOSL v1.1** @ [OSI](https://opensource.org/licenses/CATOSL-1.1). Is this intended or shall we expect an update?

**Comment by pegacat** [comment]
No, the 'CA OSL v1.0' was created fourteen years ago when JXplorer was
first made open source.  While we are very grateful to CA for the initial
donation, CA is no longer associated with the JXplorer project.

The original CA OSL v1.0 licence was based very, very closely on the Apache
licence that was popular circa 2002 - I haven't evaluated the new version
of the CA licence, however it may be more restrictive than the original,
and as such would not be compatible with the intent of people who have
contributed code to JXplorer since 2002.



-----
*Dr Christopher Betts*
JXplorer Open Source Project
http://jxplorer.org

**Comment by dacbarbos** [comment]
I agree. Thank you for the answer & clarification.
